services:
  nginx:
    image: "nginx:latest"
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
  php:
    image: "php:8.2-fpm"
    expose:
      - 9000
    volumes:
      - ./:/var/www/html
